name: Delete Action

on:
  repository_dispatch:
    types: [delete_action]
  workflow_dispatch:

jobs:
  delete_canceled_actions:
    name: Delete Action
    runs-on: ubuntu-latest
    steps:
      - name: Delete Action
        run: |
          sleep 20
          curl -i -u PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }} -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LibreScore/docs/actions/runs/${{ github.event.client_payload.run_id }}
