name: Delete Action

on:
  repository_dispatch:
    types: [delete_action]
  workflow_dispatch:

jobs:
  delete_canceled_actions:
    name: Delete Action
    runs-on: ubuntu-latest
    steps:
      - name: Delete Action
        run: |
          sleep 10
          curl -i -u ${{ secrets.LIBRESCORE_USERNAME }}:${{ secrets.LIBRESCORE_TOKEN }} -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.event.client_payload.repo }}/actions/runs/${{ github.event.client_payload.run_id }}
